import re
import json
import hashlib
from backend.services.risk_service import detect_risk
from backend.services.consequence_service import get_consequence

# -----------------------------
# MAIN PIPELINE
# -----------------------------
def analyze_contract(text):
    clauses = split_clauses(text)

    results = []
    seen = set()
    total_risk = 0

    for clause in clauses:
        clause = normalize_clause(clause)

        if len(clause) < 25:
            continue

        key = make_hash(clause)
        if key in seen:
            continue
        seen.add(key)

        risk, category = detect_risk(clause)
        translation = translate(clause)
        consequence = get_consequence(clause)

        total_risk += risk

        results.append({
            "original": clause,
            "category": category,
            "risk": risk,
            "translation": translation,
            "consequence": consequence
        })

    return format_response(results, total_risk)


# -----------------------------
# CLAUSE SPLITTING (IMPROVED)
# -----------------------------
def split_clauses(text):
    text = text.replace("\n", " ")
    text = re.sub(r'\s+', ' ', text)

    raw = re.split(r'(?<=[.;!?])\s+|•|\n', text)

    cleaned = []
    for c in raw:
        c = normalize_clause(c)

        if len(c) < 25:
            continue

        if len(c.split()) < 6:
            continue

        cleaned.append(c)

    return cleaned[:10]


# -----------------------------
# NORMALIZATION (IMPORTANT FIX)
# -----------------------------
def normalize_clause(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    noise_phrases = [
        "sample privacy policy template",
        "privacy policy",
        "terms of service",
        "last updated on date",
        "generated by termsfeed"
    ]

    for n in noise_phrases:
        text = text.replace(n, "")

    return text.strip()


# -----------------------------
# HASH FOR DEDUP
# -----------------------------
def make_hash(text):
    return hashlib.md5(text.encode()).hexdigest()



# -----------------------------
# TRANSLATION (USEFUL VERSION)
# -----------------------------
def translate(text):
    t = text.lower()

    if any(x in t for x in ["data", "privacy", "personal", "cookie"]):
        return "In simple terms: This clause explains how your personal data may be collected, used, or shared."

    if any(x in t for x in ["payment", "fee", "billing", "charge"]):
        return "In simple terms: This clause explains payments, fees, or billing rules."

    if any(x in t for x in ["terminate", "suspend", "ban", "remove"]):
        return "In simple terms: This clause explains when your access can be restricted or removed."

    return "In simple terms: This clause defines service rules, rights, or conditions."



# -----------------------------
# FINAL RESPONSE FORMAT
# -----------------------------
def format_response(clauses, total_risk):

    avg_risk = int(total_risk / max(1, len(clauses)))
    avg_risk = min(100, avg_risk)

    # TRUE DEDUP FOR SIMULATOR
    unique_consequences = []
    seen = set()

    for c in clauses:
        key = (
            c["consequence"].get("title", ""),
            c["consequence"].get("description", ""),
            c["consequence"].get("impact", "")
        )

        if key not in seen:
            seen.add(key)
            unique_consequences.append(c["consequence"])

    return {
        "analysis": {
            "clauses": clauses
        },

        "consequence_simulator": {
            "preview": "If you accept this agreement, the following impacts may occur:",
            "items": unique_consequences
        },

        "risk_dashboard": {
            "overall_risk": avg_risk,
            "verdict": verdict(avg_risk)
        }
    }


# -----------------------------
# VERDICT
# -----------------------------
def verdict(score):
    if score < 40:
        return "Safe 🟢"
    elif score < 70:
        return "Caution 🟡"
    else:
        return "Dangerous 🔴"